# Project: DungeonGame
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = DungeonGame.o
LINKOBJ  = DungeonGame.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -LC:/Users/72914/Desktop/work3/SDL2/lib -lmingw32 -lSDL2main -lSDL2 -LC:/Users/72914/Desktop/work3/SDL2_ttf/lib -lSDL2_ttf -lSDL2_image -pg
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = DungeonGame.exe
CXXFLAGS = $(CXXINCS) -pg -fexec-charset=gbk -IC:\Users\72914\Desktop\work3\SDL2\include -IC:\Users\72914\Desktop\work3\SDL2_ttf\include -IC:\Users\72914\Desktop\work3\SDL2_image\include
CFLAGS   = $(INCS) -pg -fexec-charset=gbk -IC:\Users\72914\Desktop\work3\SDL2\include
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

DungeonGame.o: DungeonGame.cpp
	$(CPP) -c DungeonGame.cpp -o DungeonGame.o $(CXXFLAGS)
